sudo: required
dist: trusty
language: node_js
node_js:
- node
before_script:
- npm install
script: 
deploy:
  app: minetest-checker
  provider: heroku
  api_key:
    secure: dnquarigFfSdTN7/0fLG6PD240hbZxev4x5IXW0khz11Pg5hrljxjrd9F3nSmWegzHmIOZIUENRntC5/APgydfnIYpHzXPceyEkU0FvwaIqdwDBzxQkWuiTR0BHIqvcFgvCoAqyiV4WOqBJici8KYbk4vCInyAZEPG41SNt9XrTwdyiaJo2JzEMEbl5AnR7brE8JB17l8mfUNs+au7cXZdIrP5yC97MYiyGzd8F2Y0MsfyFnpO79NU4XydbGG0rvyIJDWHDfWiDRA3YIrCDlWLi1FivWvNRDCVdLasWkq3ClSz31tPM7Ea7db4MPT8fcL0Tx01pbQhcnY0xbdOf48gROXACp/cHUVJZERd67DmeXnS85XTl+/ntOw5murV0LU7NKf0own6PFxkip2QdwD12HlgzUUgPC6ZfZ6eyDQmcZ1ZOnfIikObXFvAx554DH8JqEcyTElk1+cPsWwre7uAA0psHCjsp+4jNrp2+osWXwN2o029KVxloA85mI1RXJ4ARNziAGcv9M9MT5sHRgXPBzbjN92LxC/hrmaKGN1qOkfseqlaR5YtaBihdmYNUXpCHDjX+gLwB3eV0SWdqh0ovMBi2ZKguL8gPDPiK0SFemyb58dd/p+HYYDBt4caAG50IfZtferkSLztQq6R+zQWKpWqokPRr3oVdE2uz6FW0=
